package db

import (
	"context"
	"fmt"
	"os"
	"path/filepath"

	vecos "github.com/Kaffyn/Vectora/core/os"
	"github.com/philippgille/chromem-go"
)

// ChromemStore wraps chromem-go with persistent storage.
// Embeddings must be pre-generated by the LLM provider (Gemini, Claude, etc.)
// and passed in Chunk.Vector. ChromemStore only stores and retrieves — it does NOT
// call remote APIs for embedding. This keeps the vector DB as a pure storage layer.
type ChromemStore struct {
	db *chromem.DB
}

// NewVectorStore initializes folder-based persistence for embeddings using chromem-go.
func NewVectorStore() (*ChromemStore, error) {
	osMgr, err := vecos.NewManager()
	if err != nil {
		return nil, err
	}
	baseDir, _ := osMgr.GetAppDataDir()
	path := filepath.Join(baseDir, "data", "chroma")
	return NewVectorStoreAtPath(path)
}

func NewVectorStoreAtPath(path string) (*ChromemStore, error) {
	if err := os.MkdirAll(path, 0755); err != nil {
		return nil, err
	}

	db, err := chromem.NewPersistentDB(path, false)
	if err != nil {
		return nil, fmt.Errorf("vectora_internal_err: silent failure in chromem persistent db binding: %w", err)
	}

	return &ChromemStore{db: db}, nil
}

// UpsertChunk adds or updates a chunk in the vector store.
// Chunk.Vector MUST contain the pre-generated embedding from the LLM provider.
// ChromemStore does NOT generate embeddings — it only stores pre-computed vectors.
func (s *ChromemStore) UpsertChunk(ctx context.Context, collection string, chunk Chunk) error {
	if len(chunk.Vector) == 0 {
		return fmt.Errorf("chunk.Vector is empty — embeddings must be pre-generated by the LLM provider")
	}

	c, err := s.db.GetOrCreateCollection(collection, nil, nil)
	if err != nil {
		return err
	}

	doc := chromem.Document{
		ID:        chunk.ID,
		Content:   chunk.Content,
		Metadata:  chunk.Metadata,
		Embedding: chunk.Vector,
	}

	return c.AddDocument(ctx, doc)
}

// Query performs a vector similarity search using a pre-computed query embedding.
// queryVector must be generated by the same LLM provider used for indexing.
func (s *ChromemStore) Query(ctx context.Context, collection string, queryVector []float32, topK int) ([]ScoredChunk, error) {
	if len(queryVector) == 0 {
		return nil, fmt.Errorf("queryVector is empty — query embedding must be generated by the LLM provider")
	}

	c, err := s.db.GetOrCreateCollection(collection, nil, nil)
	if err != nil {
		return nil, err
	}

	res, err := c.QueryEmbedding(ctx, queryVector, topK, nil, nil)
	if err != nil {
		return nil, err
	}

	var results []ScoredChunk
	for _, doc := range res {
		results = append(results, ScoredChunk{
			Chunk: Chunk{
				ID:       doc.ID,
				Content:  doc.Content,
				Metadata: doc.Metadata,
				Vector:   doc.Embedding,
			},
			Score: doc.Similarity,
		})
	}

	return results, nil
}

func (s *ChromemStore) DeleteCollection(ctx context.Context, collection string) error {
	return s.db.DeleteCollection(collection)
}

func (s *ChromemStore) CollectionExists(ctx context.Context, collection string) bool {
	c := s.db.GetCollection(collection, nil)
	return c != nil
}
